TP INTEGRADOR- LOTE FP Y PORCENTAJE CANTIDAD VENDIDA:


#include <iostream>

using namespace std;

int main()
{
    //lote carga de formas de pago:

    char codFP[5];
    string nomFP[5];
    float porcentajes[5];
    int i;
    for(i=0;i<5;i++):{
        cout<<"Ingrese el còdigo de forma de pago(EF,MP,TR,TC,CT): ";
        cin>>codFP[i];

        cout<<"Ingrese el Nombre de la Forma de Pago: ";
        cin>>nomFP[i];

        cout<<"Ingrese el Porcentaje de descuento o interés."endl;
        cout<<"Si es un descuento, ingrese un numero negativo. Si es con interès, ingrese un numero positivo."endl;
        cin>>porcentajes[i];
    }

    //PUNTO 2: PORCENTAJE DE VENTAS POR CADA MEDIO DE PAGO.

    float porcentajeCantVendidaFP(codFP[5],Cant[],porcentajesCantVendida[5]):
        acuCant=0;
        FP=1;
        while(FP=1):

        acuCant+=Cant[]; //acumula TODAS las cantidades vendidas

        //El usuario ve el monto acumulado hasta el momento del medio de pago. 
        cout<<"Seleccione el monto acumulado de su medio de pago:";
        switch
        case 1:
            cout<<"Monto acumulado hasta el momento: Efectivo";
            codFP[i]="EF";
            acuCantEF+=Cant;
            cout<<acuCantEf;
        case 2:
            cout<<"Monto acumulado hasta el momento: Mercado Pago";
            codFP[i]="MP";
            acuCantMP+=Cant;
            cout<<acuCantMP;
        case 3:
            cout<<"Monto acumulado hasta el momento: Transferencia";
            codFP[i]="TR";
            acuCantTR+=Cant;
            cout<<acuCantTR;
        case 4:
            cout<<"Monto acumulado hasta el momento: Tarjeta de crèdito";
            codFP[i]="TC";
            acuCantTC+=Cant;
            cout<<acuCantTC;
        case 5:
            cout<<"Monto acumulado hasta el momento: Criptomonedas";
            codFP[i]="CT";
            acuCantCT+=Cant;
            cout<<acuCantCT;
        case 6:
            cout<<"Salir";
            FP=2;

            //el usuario elige el porcentaje de cant vendida del medio de pago
        switch
        cout<<"Seleccione el porcentaje de cantidad vendida del medio de pago que desea ver";
        case 1:
            cout<<"Porcentaje de cantidad vendida: Efectivo";
            float porcentaje(acuCantEF,Cant);
            cout<<pce;
        case 2:
            cout<<"Porcentaje de cantidad vendida: Mercado Pago";
            float porcentaje(acuCantMP,Cant);
            cout<<pce;
        case 3:
            cout<<"Porcentaje de cantidad vendida: Transferencia";
            float porcentaje(acuCantTR,Cant);
            cout<<pce;
        case 4:
            cout<<"Porcentaje de cantidad vendida: Tarjeta de crèdito";
            float porcentaje(acuCantTC,Cant);
            cout<<pce;
        case 5:
            cout<<"Porcentaje de cantidad vendida: Criptomonedas";
            float porcentaje(acuCantCM,Cant);
            cout<<pce;
        case 6:
            cout<<"Salir";

        //FUNCION CALCULA PORCENTAJE.
        float porcentaje(int num1, int num2):
            pce[5]=(num1*100)/num2;
            return pce;
--------------------------------------------------

//3. ventas por marca y fp
    float acuEF[]={};
    float acuMP[]={};
    float acuTR[]={};
    float acuTC[]={};
    float acuCT[]={};
    int i;
    while (nroCompra=!0):{
        for(i=0;i<10,i++):{
            if codProd==codProd[i];
                codProd[i];
                codMarca[i];
                indice=i;
                switch():
                    cout<<"Seleccione un medio de pago";
                    cout<<"1.Efectivo, 2.Mercado Pago, 3.transferencia, 4.tarjeta de credito, 5.criptomonedas";
                case 1:
                    //efectivo
                    acuEF[INDICE]+=Cant;
                case 2:
                    //Mercado pago
                    acuMP[INDICE]+=Cant;
                case 3:
                    //transferencia
                    acuTR[INDICE]+=Cant;
                case 1:
                    //Tarjeta credito
                    acuTC[INDICE]+=Cant;
                case 1:
                    //Criptomonedas
                    acuCT[INDICE]+=Cant;
            for(i=0;i<10,i++):{
                cout<<"Total de ventas efectivo:",acuEF[i],"Codigo de marca",codMarca[i];
                cout<<"Total de ventas Mercado Pago:",acuMP[i],"Codigo de marca",codMarca[i];
                cout<<"Total de ventas transferencia:",acuTR[i],"Codigo de marca",codMarca[i];
                cout<<"Total de ventas tarjeta de crèdito:",acuTC[i],"Codigo de marca",codMarca[i];
                cout<<"Total de ventas criptomoneda:",acuCT[i],"Codigo de marca",codMarca[i];
            }
        }
    }
//4.productos sin ventas
    void productoSinVentas(bool Vprod[20],int NroCompra,){
        bool Vprod[20]=false;
        for(i=0;i<20;i++):{
            Vprod[20]=false;
        }
        while(NroCompra!=0){
            Vprod[20-1]=True;
        }
        for (i=0;i<20,i++):
        if (Vprod[20]==false):{
            cout<<"Productos sin ventas;", Vprod[20];
        }
    }
    

    return 0;
-----------------
5- 5. Top 10 clientes + sorteo de cupones:
		int codCliente[50]
        NroCompra[]:    
        int max[50]: {};    

	for (int i = 0; i < nroCompra; i++) {
		if (codCliente[i] == nroCompra[i]) {
			//un vector contador, si el codigo de cliente y el de compra coinciden,
			//se le suma uno al contador, es la cantidad de nros de compras que coinciden con el
			//codigo de cliente, o sea, la cant de compras que hizo cada cliente.
			int conNroCompra[50];
			conNroCompra[i]+=1;
		}
		//funcion ordenar vector de menor a mayor
		void ordenarVector(int v[], int tam ) {
			int i,j, posmin, aux;
			for(i=0; i<tam-1; i++) {
				posmin=i;
				for(j=i+1; j<tam; j++) {
					if(v[j]<v[posmin]) posmin=j;
				}
				aux=v[i];
				v[i]=v[posmin];
				v[posmin]=aux;
			}
	//llamo a la funcion para ordenar de menor a mayor
	
	ordenarVector(cantNroCompra, 50);
	
		//agarro los ultimos 10 y los pongo en un vector maximo:
	for (int i=0;i<10; i++): {
    MAX[i]=cantNroCompra[40 + i];
    }
	
	for(i=0;i<10,i++):{
	    cout<<"Los 10 clientes con mas compras realizadas: ";
	    cout<<codCliente[i], MAX[i];
		}
	//cargarAleatorio
	void cargarAleatorio(int v[], int tam, int limite){
    int i;
    for( i=0; i<tam; i++ ){
        v[i]=(rand()%limite)+1;
    }
     void mostrarVector(int v[], int tam){
    int i;
    for(i=0;i<tam;i++){
        cout<<v[i]<<"\t";
    }
    //Llamo a la funcion para cargar cargarAleatorio
    
    void cargarAleatorio(codCliente[],int 3, int 50);
    cout<<"l@S 3 GANADOR@S DEL SORTEO DE CUPONES DE DESCUENTO SON: "
    //llamo a la funcion mostrarVector para que imprima los 3 num aleatorios
    void mostrarVector(int codCliente[], int 3, int 50);




}
